version: "3"
services:
    snappymail-docker:
        stdin_open: true
        tty: true
        ports:
            - 80:80
            - 443:443
        restart: unless-stopped
        volumes:
            - $(pwd)/volumes/var-www-snappymail-data:/var/www/snappymail/data
            - $(pwd)/volumes/etc-apache2-sites-available:/etc/apache2/sites-available
            - $(pwd)/volumes/var-log-apache2:/var/log/apache2/
            - $(pwd)/volumes/usr-local-etc-php-conf.d/increase-upload-size.ini:/usr/local/etc/php/conf.d/increase-upload-size.ini
            - /etc/letsencrypt/:/etc/letsencrypt/:ro
        container_name: snappymail
        image: docker.io/xgbstar1/snappymail-docker:main